#!/bin/sh
 
C=SP
ST=Granada
L=Atarfe
O=Iliberis.com
OU=Asir
CN=0
correo=0
read -p "Introduce nombre de usuario : " CN
read -p "Introduce correo de usuario : " correo
csr="${CN}.csr"
key="${CN}.key"
cert="${CN}.crt"

#crear key
openssl genrsa -out $key 2048

# Create the certificate signing request
openssl req -new -key $key -out $csr <<EOF
${C}
${ST}
${L}
${O}
${OU}
${CN}
${correo}
.
.
EOF
#Crea el Certificado
openssl x509 -req -in ${csr} -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out ${cert} -days 1000 -sha256

####Definimos lor parametros de conexion a la BBDD mysql
SQL_HOST="localhost"
SQL_USER="root"
SQL_PASSWORD="root"
SQL_DATABASE="proximity"
####Montamos los parametros de conexión.
SQL_ARGS="-h $SQL_HOST -u $SQL_USER -p$SQL_PASSWORD -D $SQL_DATABASE -s -e"
#### Montamos la sentencia SQL y la lanzamos
mysql $SQL_ARGS "INSERT INTO client (pin, cert, firstname, email) VALUES ('', '${C}', '${CN}', '${correo}');"
var=$(mysql $SQL_ARGS "SELECT pin from client order by pin desc limit 1;")
echo $var
dir=$(($var % 20))
echo $dir
if [ -d /opt/$dir ];
then
	mkdir /opt/$dir/$HOST
	mv $cert $key $csr /opt/$dir/$HOST
else
	mkdir /opt/$dir/
	mkdir /opt/$dir/$HOST
	mv $cert $key $csr /opt/$dir/$HOST
fi

